version: '2.1'
services:
  xud:
    image: exchangeunion/xud:latest
    build:
      context: xud/
    volumes:
      - ../:/opt/xud
      - /opt/xud/node_modules
      - ./xud:/root/.xud
    ports:
      - "8885"
      - "8886"
    networks:
      - xud
    depends_on:
      - db
      - lnd_btc
      - lnd_ltc
    entrypoint: "npm run run"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "xud"
      MYSQL_USER: "xud"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - xud
  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btc:
    image: btcd
    build:
      context: btcd/
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
  btcd:
    extends: btc
    container_name: btcd
    environment:
      - DEBUG
      - MINING_ADDRESS
    entrypoint: ["./start-btcd.sh"]
  # ltc is an image of litecoin node which used as base image for ltcd and
  # ltcctl. The environment variables default values determined on stage of
  # container start within starting script.
  ltc:
    image: ltcd
    build:
      context: ltcd/
    volumes:
          - shared:/rpc
          - litecoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
  ltcd:
      extends: ltc
      container_name: ltcd
      environment:
        - DEBUG
        - MINING_ADDRESS
      entrypoint: ["./start-ltcd.sh"]
  lnd:
      image: lnd
      build:
        context: lnd/
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
          - shared:/rpc
      entrypoint: ["./start-lnd.sh"]
  lnd_ltc:
    extends: lnd
    container_name: lnd_ltc
    links:
      - "ltcd:blockchain"
    networks:
      - xud
  lnd_btc:
    extends: lnd
    container_name: lnd_btc
    links:
      - "btcd:blockchain"
    networks:
      - xud
volumes:
  # db-data volume is needed for maintaining mysql persistence
  # during db container recreation.
  db-data:
    driver: local

  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during ltcd container recreation.
  litecoin:
    driver: local

networks:
  xud:

