version: '2.1'
services:
  xud:
    image: exchangeunion/xud:latest
    build:
      context: xud/
    volumes:
      - ../:/opt/xud
      - /opt/xud/node_modules
      - ./xud:/root/.xud
      - shared:/root/.lnd/
    ports:
      - "8885"
      - "8886"
    networks:
      - xud
    depends_on:
      - btc
      - lnd
    entrypoint: "npm start"
  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btc:
    image: btcd
    build:
      context: btcd/
    container_name: btcd
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    entrypoint: ["./start-btcd.sh"]
    networks:
      - xud
  lnd:
    image: lnd
    build:
      context: lnd/
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared:/rpc
      - shared:/root/.lnd/
    entrypoint: ["./start-lnd.sh"]
    networks:
      - xud
volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local
  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

networks:
  xud:

