name: Seedutil

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [14.x]
        go-version: [1.13.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile:seedutil

      - name: Test
        run: npm run test:seedutil
